config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :planes do
    resources :bookings, only: [ :create ]
  end
  resources :bookings, only: [ :index, :edit, :update, :show ]
  resources :plane_models, only: [ :create, :update, :edit ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :plane
  belongs_to :user

  enum status: { pending: 0, confirmed: 1, declined: 2, accepted: 3, cancelled: 4, paid: 5 }
  # validates :end_date, comparison: { greater_than_or_equal_to: :start_date }

  validates :status, :start_date, :end_date, presence: true

  validate :end_date_is_after_start_date

  private

  def end_date_is_after_start_date
    return if end_date.blank? || start_date.blank?

    errors.add(:end_date, "cannot be before the start date") if end_date < start_date
  end
end

app/models/plane.rb
class Plane < ApplicationRecord
  belongs_to :plane_model
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_one_attached :photo

  validates :name, :price, :plane_model_id, presence: true
end

app/models/plane_model.rb
class PlaneModel < ApplicationRecord
  has_many :planes, dependent: :destroy

  validates :seats, :horsepower, :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bookings, dependent: :destroy
  has_many :planes, dependent: :destroy
  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/ # || controller_name == "bookings"
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:user_name, :first_name, :last_name, :photo])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_plane, only: [ :create ]
  before_action :set_booking, only: [ :update ]
  def index
    @bookings = policy_scope(Booking) # current_user.bookings policy_scope(Booking)
    @user_planes = current_user.planes
    @sorted_bookings = @bookings.order('start_date ASC')
  end

  def show; end

  def new
    # @plane = Plane.find(params[:plane_id])
    @booking = Booking.new
    authorize @booking
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.plane = @plane
    @booking.user = current_user
    authorize @booking
    if @booking.save
      redirect_to bookings_path
    else
      render :new
    end
  end

  def edit; end

  def update
    index
    authorize @booking
    @booking.update(booking_params)
    render :index
  end


  # { pending: 0, confirmed: 1, declined: 2, accepted: 3, cancelled: 4, paid: 5 }
  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def set_plane
    @plane = Plane.find(params[:plane_id])
  end

  def booking_params
    params.require(:booking).permit(:status, :start_date, :end_date)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
    @planes = policy_scope(Plane)
  end
end

app/controllers/plane_models_controller.rb
class PlaneModelsController < ApplicationController
  def create
  end

  def update
  end

  def edit
  end
end

app/controllers/planes_controller.rb
class PlanesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home, :show]
  before_action :set_planes, only: [ :show, :edit, :update ]

  def index
    @planes = policy_scope(Plane)
  end

  def show
    if @plane.availability == false
      redirect_to root_path
    end
    authorize @plane
    @booking = Booking.new(plane: @plane)
  end

  def new
    @plane = Plane.new
    authorize @plane
  end

  def create
    @plane = Plane.new(plane_params)
    @plane.user = current_user
    authorize @plane
    if @plane.save
      redirect_to plane_url(@plane), alert: "Watch it, mister!"
    else
      render :new
    end
  end

  def edit
    authorize @plane
  end

  def update
    authorize @plane
    @plane.update(plane_params)

    if @plane.availability
      redirect_to plane_path(@plane)
    else
      redirect_to root_path
    end
  end

  def destroy; end

  private

  def set_planes
    @plane = Plane.find(params[:id])
  end

  def plane_params
    params.require(:plane).permit(:name, :price, :availability, :description, :plane_model_id, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<section class="pt-5">
<div class="container">
  <div class="row mt-5 mb-1">
  <div class="col-12">
      <h1>Hello <%= current_user.first_name %> welcome to your plane world!</h1>
  </div>
  </div>
  <div class="row my-5">
  <div class="col-12">
      <h2>Your bookings</h2>
  </div>
  </div>
  <div class="row my-5 justify-content-center">
  <div class="col-12">
    <div class="cards">
      <% @sorted_bookings.each do |booking| %>
      <%= link_to plane_path(booking.plane), class: "card-trip" do %>
          <% if booking.plane.photo.attached? %>
            <div class="card-trip-banner">
            <div class="card-trip-banner-img" style="background-image: linear-gradient(rgba(41, 67, 78, 0.05), rgba(41, 67, 78, 0.65)), url(<%= cl_image_path booking.plane.photo.key, crop: :fill %>);">
            </div>
              <div class="tag <%= booking.status %>" ><%= booking.status %></div>
            </div>
          <% else %>
            <div class="card-trip-banner">
            <div class="card-trip-banner-img" style="background-image: linear-gradient(rgba(41, 67, 78, 0.05), rgba(41, 67, 78, 0.65)), url(https://res.cloudinary.com/dy5wj4h8e/image/upload/v1644058464/development/iyzm9gfvo7o9k2xupglcdcy23cwq.jpg);">
            </div>
               <div class="tag <%= booking.status %>" ><%= booking.status %></div>
            </div>
          <% end %>
          <div class="card-trip-infos">
          <div>
            <h4><%= booking.plane.name.truncate(27) %></h4>
            <p><%= booking.plane.plane_model.name %></p>
            <div class="card-trip-infos2">
              <p class="card-description2"><span class="date-span">From</span><br/><strong><%= booking.start_date.strftime("%d.%m.%Y")%></strong></p>
              <p class="card-description2"><span class="date-span">To</span><br/><strong><%= booking.end_date.strftime("%d.%m.%Y")%></strong></p>
            </div>
            <div class="card-trip-infos2">
              <p class="card-description"><strong>Overall: <%=  number_with_delimiter((((booking.end_date - booking.start_date).to_i + 1) * (booking.plane.price / 100)), options = {}) %> €</strong></p>
              <p class="card-description"><strong><%=  number_with_delimiter((booking.plane.price / 100), options = {}) %> €</strong> / day</p>
            </div>
          </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
  </div>
</div>
</section>
<section class="py-5">
<div class="container">
  <div class="row my-5">
    <div class="col-12">
    <h3>Your requests</h3>
    </div>
  </div>
  <div class="row my-5 justify-content-center">
  <div class="col-12">

  <div class="cards">
    <% @user_planes.each do |user_plane| %>
      <% user_plane.bookings.order(:status).each do |booking| %>
        <div class="card-trip">
        <% if booking.plane.photo.attached? %>
          <div class="card-trip-banner">
            <div class="card-trip-banner-img" style="background-image: linear-gradient(rgba(41, 67, 78, 0.05), rgba(41, 67, 78, 0.65)), url(<%= cl_image_path user_plane.photo.key, crop: :fill %>);">
            </div>
            <div class="tag <%= booking.status%>"><%= booking.status %></div>
          </div>
          <% else %>
            <div class="card-trip-banner">
            <div class="card-trip-banner-img" style="background-image: linear-gradient(rgba(41, 67, 78, 0.05), rgba(41, 67, 78, 0.65)), url(https://res.cloudinary.com/dy5wj4h8e/image/upload/v1644058464/development/iyzm9gfvo7o9k2xupglcdcy23cwq.jpg);">
            </div>
            <div class="tag <%= booking.status%>"><%= booking.status %></div>
          </div>
          <% end %>
          <div class="card-trip-infos">
            <h4><%= link_to user_plane.name, plane_path(user_plane) %></h4>
            <p><%= booking.plane.plane_model.name %></p>
            <div class="card-trip-infos2">
              <p class="card-description2"><span class="date-span">From</span><br/><strong><%= booking.start_date.strftime("%d.%m.%Y")%></strong></p>
              <p class="card-description2"><span class="date-span">To</span><br/><strong><%= booking.end_date.strftime("%d.%m.%Y")%></strong></p>
            </div>
            <div class="card-trip-infos2">
              <p class="card-description"><strong>Total earnings: <%=  number_with_delimiter((((booking.end_date - booking.start_date).to_i + 1) * (booking.plane.price / 100)), options = {}) %> €</strong></p>
              <p class="card-description"><strong><%=  number_with_delimiter((booking.plane.price / 100), options = {}) %> €</strong> / day</p>
            </div>
            <div>
              <% if booking.status == "pending" %>
              <div class="d-flex m-card-negative-cta">
                <%= simple_form_for booking , html: { class: "w-50"} do |f| %>
                  <%# <%= f.input :status, as: :hidden, input_html: { status: 1 } %>
                  <%= f.input :status, as: :hidden, input_html: { value: "confirmed" } %>
                  <%= f.submit "Confirm", class: "cta cta-dark w-100" %>
                <% end %>
                <%= simple_form_for booking , html: { class: "w-50"} do |f| %>
                  <%= f.input :status, as: :hidden, input_html: { value: "declined" } %>
                  <%= f.submit "Decline", class: "cta cta-light w-100" %>
                <% end %>
              </div>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
  </div>
  </div>
</div>
</section>

app/views/bookings/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-6">
      <%= simple_form_for [ @plane, @booking ] do |f| %>
        <%= f.input :status, as: :hidden, input_html: { status: 0} %>
        <%= f.input :start_date, as: :date, html5: true %>
        <%= f.input :end_date, as: :date, html5: true %>
        <%= f.submit "Book", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PlainPlane</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= favicon_link_tag asset_path('favicon-32x32.png') %>
    <%= image_tag "plainplane.png", class: "avatar" %>
  </head>
  <body class="d-flex flex-column min-vh-100">
    <%= render 'shared/navbar' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="content">
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
    <div class="banner" style="background-image: linear-gradient(rgba(41, 67, 78, 0.25), rgba(41, 67, 78, 1)), url('assets/hero.jpeg');">
      <div class="container text-center">
        <h1>Jets are for cool people!</h1>
        <p class="mb-3">Change your life and rent a jet, become 007.</p>
        <a class="cta cta-light" href="#plane-overview">fly now</a>
      </div>
    </div>
<section class="dark py-5 margin-top-negative-section">
<div class="container">
  <div class="row my-5 justify-content-center">
    <div class="col-6 text-center">
      <h2 class="primary-text">Book your private jet today and escape your boring life.</h2>
    </div>
  </div>
  <div class="row mb-5 justify-content-around">
    <div class="col-8 col-lg-3 text-center mb-5 mb-lg-0">
    <i class="fas fa-plane fa-3x text-light"></i>
      <h3 class="pb-2 pt-4 primary-text">Your own jet</h3>
      <p class="primary-text">You hate travelling like everyone else? Start to do it like the cool ones, with your own plane.</p>
    </div>
    <div class="col-8 col-lg-3 text-center mb-5 mb-lg-0">
    <i class="fas fa-rainbow fa-3x text-light"></i>
      <h3 class="pb-2 pt-4 primary-text">No limits</h3>
      <p class="primary-text">You don't want to stick to normal standards? Book your own plane and decide the destinations as you want.</p>
    </div>
    <div class="col-8 col-lg-3 text-center mb-5 mb-lg-0">
      <i class="fas fa-clock fa-3x text-light"></i>
      <h3 class="pb-2 pt-4 primary-text">On demand</h3>
      <p class="primary-text">Find the perfect plane for you and book it now for tomorrow. Fasten your seatbelt and enjoy your trip.</p>
    </div>
  </div>
  </div>
</section>
<section class="py-5">
<div class="container">
<div class="row my-5 justify-content-center">
    <div id="plane-overview" class="col-6 text-center">
      <h2>Find the best planes on earth and mars</h2>
    </div>
</div>
  <div class="row mb-5 justify-content-center">
  <div class="col-12">
    <div class="cards">
      <% @planes.each do |plane| %>
      <%= link_to plane_path(plane), class: "card-trip" do %>
          <div class="img-wrapper">
            <% if plane.photo.attached? %>
              <%= cl_image_tag plane.photo.key, crop: :fill %>
            <% else %>
              <img src="https://res.cloudinary.com/dy5wj4h8e/image/upload/v1644058464/development/iyzm9gfvo7o9k2xupglcdcy23cwq.jpg" />
            <% end %>
          </div>
          <div class="card-trip-infos">
            <div>
              <h4><%= plane.name.truncate(27) %></h4>
              <div class="card-trip-infos2">
                <p><%= plane.plane_model.name %></p>
                <p class="card-description"><strong><%= number_with_delimiter((plane.price / 100), options = {}) %> €</strong> / day </p>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
  </div>
</div>
</section>

app/views/planes/edit.html.erb
<section class="py-5">
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-md-6">
      <div class="form-card">
        <h3>Update your plane listing</h3>
          <%= render "shared/form", plane: @plane %>
      </div>
    </div>
  </div>
</div>
</section>

app/views/planes/new.html.erb
<section class="py-5">
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-md-6">
      <div class="form-card">
        <h3>Create a plane list</h3>
          <%= render "shared/form", plane: @plane %>
      </div>
    </div>
  </div>
</div>
</section>

app/views/planes/show.html.erb
<div class="container mb-5">
  <div class="row mt-5 mb-1">
    <div class="col-12">
    <h1><%= @plane.name %></h1>
    </div>
  </div>
  <% if policy(@plane).edit? %>
  <div class="row mb-1">
    <div class="col-12">
    <div class="d-flex align-items-end justify-content-end">
      <%= link_to 'Edit', edit_plane_path(@plane), class: "simple-link mr-3" %>
      <% if @plane.availability %>
        <%= simple_form_for @plane do |f| %>
          <%= f.input :availability, as: :hidden, input_html: { value: false } %>
          <%= f.submit "Delete", class: 'simple-link-delete' %>
        <% end %>
      <% end %>
    </div>
    </div>
  </div>
  <% end %>
  <div class="row mb-5">
    <div class="col-12">
    <% if @plane.photo.attached? %>
      <div class="banner" style="background-image:  url('<%= cl_image_path @plane.photo.key %>');"></div>
    <% else %>
      <div class="banner" style="background-image:  url('https://res.cloudinary.com/dy5wj4h8e/image/upload/v1644058464/development/iyzm9gfvo7o9k2xupglcdcy23cwq.jpg');"></div>
    <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-12 col-lg-7 mb-5">
      <div class="plane-card">
        <h3><%= @plane.plane_model.name %></h3>
          <div class="light-border-bottom">
            <ul class="list-inline mb-0">
              <li class="list-inline-item">
                <i class="fas fa-chair"></i> <%= @plane.plane_model.seats %>
              </li>
              <li class="list-inline-item">
                <i class="fas fa-horse"></i> <%= @plane.plane_model.horsepower %>
              </li>
              <li class="list-inline-item">
                <i class="fas fa-user"></i> <%= @plane.user.user_name %>
              </li>
            </ul>
          </div>
          <p class="mt-3 mb-0"><%= @plane.description %></p>
      </div>
    </div>
  <div class="col-12 col-lg-5">
    <div class="plane-card">
      <p><span style="font-size: 24px;"><strong><%= number_with_delimiter((@plane.price / 100), options = {}) %> €</strong></span> / day<p>
      <%= simple_form_for [ @plane, @booking ] do |f| %>
        <%= f.input :status, as: :hidden, input_html: { value: "pending" } %>
        <%= f.input :start_date, as: :date, html5: true %>
        <%= f.input :end_date, as: :date, html5: true %>
        <%= f.submit "Book now", class: "cta cta-dark" %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<footer class="mt-auto">
  <div class="footer">
    <div class="footer-links">
      <a href="#"><i class="fab fa-github"></i></a>
      <a href="#"><i class="fab fa-instagram"></i></a>
      <a href="#"><i class="fab fa-facebook"></i></a>
      <a href="#"><i class="fab fa-twitter"></i></a>
      <a href="#"><i class="fab fa-linkedin"></i></a>
    </div>
    <div class="footer-copyright">
      Developed and presented by <i class="fas fa-cookie-bite"></i>
    </div>
  </div>
</footer>

app/views/shared/_form.html.erb
<%= simple_form_for (plane) do |f| %>
  <%= f.input :name, placeholder: 'Enter a name' %>
  <%= f.input :price, placeholder: 'Enter a price' %>
  <%= f.association :plane_model, collection: PlaneModel.all.order(:name), prompt: 'Select a plane',  input_html: { class: 'select2' } %>
  <%= f.input :description, placeholder: 'Describe your lovely plane' %>
  <%= f.input :availability, as: :hidden, input_html: { value: true } %>
  <%= f.input :photo, as: :file %>
  <div class="align-ctas">
    <%= f.submit class: 'cta cta-dark' %>
    <% if (current_page?(new_plane_path))%>
      <%= link_to "Cancel", root_path, class: 'hover-underline-animation my-auto' %>
    <% else %>
      <%= link_to "Cancel", plane_path(plane), class: 'hover-underline-animation my-auto' %>
    <% end %>
  </div>

<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "plainplane.png" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item my-auto mr-2">
          <% if policy(Plane).new? %>
              <%= link_to "Create offer", new_plane_path, class: "primary-text nav-link hover-underline-animation-light", style: "padding:0; color: #ffffff; text-transform: uppercase; font-weight: 500;"  %>
          <% end %>
        </li>
        <li class="nav-item dropdown">
        <% if current_user.photo.attached? %>
          <%= cl_image_tag current_user.photo.key,  gravity: :faces, height: 40, width: 40 , class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <% else %>
          <%= cl_image_tag "Avatar-PNG-Image_lifnyu.png",  gravity: :faces, height: 40, width: 40 , class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "My Bookings", bookings_path, class: "dropdown-lewagon dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-lewagon dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link primary-text hover-underline-animation-light", style: "padding:0; color: #ffffff; text-transform: uppercase; font-weight: 500;" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>